<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>EPFOptimizerPro</AssemblyName>
    <RootNamespace>EPFOptimizerPro</RootNamespace>
    <Version>3.9.36</Version>
    <AssemblyVersion>3.9.36.0</AssemblyVersion>
    <FileVersion>3.9.36.0</FileVersion>
    <InformationalVersion>3.9.36-version-only-msi-update-test</InformationalVersion>
    <Company>EPF Normandie</Company>
    <Product>EPF Optimizer Pro</Product>
    <Authors>EPF Normandie - Patrick JARDIN</Authors>
    <Description>EPF Optimizer Pro Premium avec correction des noms de contrôles, dashboard fluide et workers adaptatifs CPU/RAM.</Description>
      <ApplicationIcon>Assets\EPFOptimizerPro.ico</ApplicationIcon>
  </PropertyGroup>
</Project>















































